-- Schema inicial para banco PostgreSQL/Supabase vazio.
-- Não executar em um banco existente sem comparar antes com o schema atual.
BEGIN;

CREATE TABLE "Sistema" (
    "SistemaId" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Codigo" varchar(50) NOT NULL,
    "Nome" varchar(150) NOT NULL,
    "Ativo" boolean NOT NULL,
    "DiasTolerancia" integer NOT NULL,
    "DiasOffline" integer NOT NULL,
    "CriadoEm" timestamp without time zone NOT NULL
);
CREATE UNIQUE INDEX "IX_Sistema_Codigo" ON "Sistema" ("Codigo");

CREATE TABLE "Cliente" (
    "ClienteId" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Nome" varchar(150) NOT NULL,
    "Documento" varchar(30),
    "Email" varchar(150),
    "Telefone" varchar(30),
    "Endereco" varchar(300),
    "Numero" text,
    "Ativo" boolean NOT NULL,
    "CriadoEm" timestamp without time zone NOT NULL
);
CREATE INDEX "IX_Cliente_Nome" ON "Cliente" ("Nome");
CREATE INDEX "IX_Cliente_Documento" ON "Cliente" ("Documento");

CREATE TABLE "Instalacao" (
    "InstalacaoId" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ClienteId" integer NOT NULL,
    "SistemaId" integer NOT NULL,
    "InstalacaoKey" varchar(50) NOT NULL,
    "NomeInstalacao" varchar(150),
    "Ativa" boolean NOT NULL,
    "CriadoEm" timestamp without time zone NOT NULL,
    "UltimaComunicacao" timestamp without time zone,
    CONSTRAINT "FK_Instalacao_Cliente_ClienteId" FOREIGN KEY ("ClienteId") REFERENCES "Cliente" ("ClienteId") ON DELETE RESTRICT,
    CONSTRAINT "FK_Instalacao_Sistema_SistemaId" FOREIGN KEY ("SistemaId") REFERENCES "Sistema" ("SistemaId") ON DELETE RESTRICT
);
CREATE UNIQUE INDEX "IX_Instalacao_SistemaId_InstalacaoKey" ON "Instalacao" ("SistemaId", "InstalacaoKey");
CREATE INDEX "IX_Instalacao_ClienteId" ON "Instalacao" ("ClienteId");
CREATE INDEX "IX_Instalacao_SistemaId" ON "Instalacao" ("SistemaId");
CREATE INDEX "IX_Instalacao_UltimaComunicacao" ON "Instalacao" ("UltimaComunicacao");

CREATE TABLE "Plano" (
    "PlanoId" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "SistemaId" integer NOT NULL,
    "Codigo" varchar(50) NOT NULL,
    "Nome" varchar(100) NOT NULL,
    "DuracaoDias" integer,
    "DuracaoMeses" integer,
    "Ativo" boolean NOT NULL,
    "Valor" numeric(18,2),
    "CriadoEm" timestamp without time zone NOT NULL,
    CONSTRAINT "FK_Plano_Sistema_SistemaId" FOREIGN KEY ("SistemaId") REFERENCES "Sistema" ("SistemaId") ON DELETE RESTRICT
);
CREATE UNIQUE INDEX "IX_Plano_SistemaId_Codigo" ON "Plano" ("SistemaId", "Codigo");
CREATE INDEX "IX_Plano_SistemaId" ON "Plano" ("SistemaId");
CREATE INDEX "IX_Plano_Ativo" ON "Plano" ("Ativo");

CREATE TABLE "Licenca" (
    "LicencaId" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "OficinaId" varchar(50) NOT NULL,
    "NomeOficina" varchar(150) NOT NULL,
    "InstalacaoId" integer,
    "PlanoId" integer,
    "Ativa" boolean NOT NULL,
    "Plano" varchar(50),
    "SituacaoComercial" varchar(30) NOT NULL,
    "DataInicio" timestamp without time zone,
    "DataVencimento" timestamp without time zone,
    "UltimaValidacao" timestamp without time zone,
    "ValidaAte" timestamp without time zone,
    "Mensagem" varchar(500),
    CONSTRAINT "FK_Licenca_Instalacao_InstalacaoId" FOREIGN KEY ("InstalacaoId") REFERENCES "Instalacao" ("InstalacaoId") ON DELETE SET NULL,
    CONSTRAINT "FK_Licenca_Plano_PlanoId" FOREIGN KEY ("PlanoId") REFERENCES "Plano" ("PlanoId") ON DELETE SET NULL
);
CREATE INDEX "IX_Licenca_OficinaId" ON "Licenca" ("OficinaId");
CREATE INDEX "IX_Licenca_InstalacaoId" ON "Licenca" ("InstalacaoId");
CREATE INDEX "IX_Licenca_PlanoId" ON "Licenca" ("PlanoId");

CREATE TABLE "CredencialInstalacao" (
    "CredencialInstalacaoId" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "InstalacaoId" integer NOT NULL,
    "ChaveHash" varchar(128) NOT NULL,
    "UltimosCaracteres" varchar(8),
    "Ativa" boolean NOT NULL,
    "CriadoEm" timestamp without time zone NOT NULL,
    "UltimaUtilizacao" timestamp without time zone,
    "RevogadaEm" timestamp without time zone,
    "ChaveRecuperacaoProtegida" text,
    "RecuperacaoExpiraEm" timestamp without time zone,
    CONSTRAINT "FK_CredencialInstalacao_Instalacao_InstalacaoId" FOREIGN KEY ("InstalacaoId") REFERENCES "Instalacao" ("InstalacaoId") ON DELETE CASCADE
);
CREATE UNIQUE INDEX "IX_CredencialInstalacao_ChaveHash" ON "CredencialInstalacao" ("ChaveHash");
CREATE INDEX "IX_CredencialInstalacao_InstalacaoId" ON "CredencialInstalacao" ("InstalacaoId");
CREATE INDEX "IX_CredencialInstalacao_Ativa" ON "CredencialInstalacao" ("Ativa");
CREATE UNIQUE INDEX "UX_CredencialInstalacao_Ativa_InstalacaoId" ON "CredencialInstalacao" ("InstalacaoId") WHERE "Ativa";

CREATE TABLE "LicencaHistorico" (
    "LicencaHistoricoId" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "LicencaId" integer NOT NULL,
    "Acao" varchar(50) NOT NULL,
    "Plano" varchar(50),
    "DataInicioAnterior" timestamp without time zone,
    "DataInicioNova" timestamp without time zone,
    "DataVencimentoAnterior" timestamp without time zone,
    "DataVencimentoNovo" timestamp without time zone,
    "ValidaAteAnterior" timestamp without time zone,
    "ValidaAteNova" timestamp without time zone,
    "AtivaAnterior" boolean,
    "AtivaNova" boolean,
    "Origem" varchar(50) NOT NULL,
    "Observacao" varchar(500),
    "CriadoEm" timestamp without time zone NOT NULL,
    CONSTRAINT "FK_LicencaHistorico_Licenca_LicencaId" FOREIGN KEY ("LicencaId") REFERENCES "Licenca" ("LicencaId") ON DELETE CASCADE
);
CREATE INDEX "IX_LicencaHistorico_LicencaId" ON "LicencaHistorico" ("LicencaId");
CREATE INDEX "IX_LicencaHistorico_CriadoEm" ON "LicencaHistorico" ("CriadoEm");

CREATE TABLE "ApiRequisicao" (
    "ApiRequisicaoId" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "DataHora" timestamp without time zone NOT NULL,
    "Metodo" varchar(10) NOT NULL,
    "Rota" varchar(300) NOT NULL,
    "Aplicacao" varchar(100),
    "Operacao" varchar(100),
    "QueryString" varchar(1000),
    "StatusCode" integer,
    "DuracaoMs" bigint,
    "OficinaId" varchar(50),
    "InstalacaoId" integer,
    "ClienteId" integer,
    "SistemaId" integer,
    "PlanoId" integer,
    "Ip" varchar(100),
    "UserAgent" varchar(1000),
    "RequestContentType" varchar(200),
    "ResponseContentType" varchar(200),
    "CorrelationId" varchar(100),
    "Sucesso" boolean NOT NULL,
    "Erro" varchar(2000)
);
CREATE INDEX "IX_ApiRequisicao_DataHora" ON "ApiRequisicao" ("DataHora");
CREATE INDEX "IX_ApiRequisicao_StatusCode" ON "ApiRequisicao" ("StatusCode");
CREATE INDEX "IX_ApiRequisicao_OficinaId" ON "ApiRequisicao" ("OficinaId");
CREATE INDEX "IX_ApiRequisicao_InstalacaoId" ON "ApiRequisicao" ("InstalacaoId");
CREATE INDEX "IX_ApiRequisicao_ClienteId" ON "ApiRequisicao" ("ClienteId");
CREATE INDEX "IX_ApiRequisicao_SistemaId" ON "ApiRequisicao" ("SistemaId");
CREATE INDEX "IX_ApiRequisicao_PlanoId" ON "ApiRequisicao" ("PlanoId");
CREATE INDEX "IX_ApiRequisicao_Rota" ON "ApiRequisicao" ("Rota");
CREATE INDEX "IX_ApiRequisicao_Operacao" ON "ApiRequisicao" ("Operacao");
CREATE INDEX "IX_ApiRequisicao_Aplicacao" ON "ApiRequisicao" ("Aplicacao");
CREATE INDEX "IX_ApiRequisicao_CorrelationId" ON "ApiRequisicao" ("CorrelationId");

COMMIT;
